# Copyright 2019 ArctosLabs Scandinavia AB
# *************************************************************

# This file is part of OSM Placement module
# All Rights Reserved to ArctosLabs Scandinavia AV

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at

#         http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# For those usages not covered by the Apache License, Version 2.0 please
# contact: xxx@arctoslabs.com
##

global:
  loglevel: INFO

message:
  driver: kafka
  host: kafka
  port: 9092
  group_id: pla

database:
  driver: mongo
  host: mongo
  port: 27017
  name: osm
 
# Place Of Precence (POP), price list 
pop:
  - vim_url:http://10.234.12.47:5000/v3
    vim_name:OpenStack1
    vm_price:
    - x_large: 10
    - large: 5
    - medium: 4
    - small: 3
    - tiny: 2
  - vim_url:http://10.234.12.44:5000/v3
    vim_name:OpenStack2
    vm_price:
    - large: 10
    - medium: 8
    - small: 6
    - tiny: 4
  - vim_url:http://10.234.12.46:5000/v3
    vim_name:OpenStack3
    vm_price:
    - large: 8
    - medium: 6
    - small: 3
    - tiny: 2
  - vim_url:http://10.234.12.43:5000/v3
    vim_name:OpenStack4
    vm_price:
    - large: 9
    - medium: 7
    - small: 4
    - tiny: 3

# POP Interconnecting Link (PIL), price list and latency     
pil:
  - pil_name: vim1_vim2
  	vim1_url: :http://10.234.12.47:5000/v3
  	vim2_url: :http://10.234.12.44:5000/v3
    pil_price: 5
    pil_latency: 50
  - pil_name: vim1_vim3
  	vim1_url: :http://10.234.12.47:5000/v3
  	vim2_url: :http://10.234.12.46:5000/v3
    pil_price: 6
    pil_latency: 100
  - pil_name: vim1_vim4
  	vim1_url: :http://10.234.12.47:5000/v3
  	vim2_url: :http://10.234.12.43:5000/v3
    pil_price: 6
    pil_latency: 150
  - pil_name: vim2_vim3
  	vim2_url: :http://10.234.12.44:5000/v3
  	vim3_url: :http://10.234.12.46:5000/v3
    pil_price: 5
    pil_latency: 50
  - pil_name: vim2_vim4
  	vim2_url: :http://10.234.12.44:5000/v3
  	vim3_url: :http://10.234.12.43:5000/v3
    pil_price: 6
    pil_latency: 100
  - pil_name: vim3_vim4
  	vim2_url: :http://10.234.12.46:5000/v3
  	vim3_url: :http://10.234.12.43:5000/v3
    pil_price: 5
    pil_latency: 50
    
   
    
    
    
    
    
     
